数组链表课后作业
algorithm005-class02/algorithm005-class02 pull request #104
Opened 2019-12-14 15:47 UTC by letianxhz

2019-12-14 17:42 UTC, miniKid requested changes
一点小改进，可以省一次比较。

2019-12-14 17:42 UTC, miniKid commented on Week_01/G20190343020257/LeetCode_26_0257.java
> +        for (int i = 0; i < nums.length; ++i) {
这里i可以从1开始，第一次比较，i和j都是0，没有意义。

2019-12-15 11:30 UTC, simoncat001 commented on Week_01/G20190343020257/LeetCode_189_0257.java
> +}
反转用的很好

2019-12-15 11:30 UTC, simoncat001 commented on Week_01/G20190343020257/LeetCode_66_0257.java
> +                return digits;
这里是最牛的,节约了好多运算

2019-12-17 12:18 UTC, merged