0227-Week 01
algorithm005-class02/algorithm005-class02 pull request #69
Opened 2019-12-11 16:38 UTC by int86

0227-Week 01

2019-12-14 03:43 UTC, YinDongFang reviewed
大佬666

2019-12-14 03:43 UTC, YinDongFang commented on Week_01/G20190343020227/LeetCode_189_0227.py
> +        nums[:] = nums[n-k:] + nums[:n-k]
666👍

2019-12-14 03:43 UTC, YinDongFang commented on Week_01/G20190343020227/LeetCode_239_0227.py
> +        return re
```python []
class Solution:
    def maxSlidingWindow(self, nums, k):
        if not nums or not k:
            return []
        maxs = []
        for i in range(len(nums) - k + 1):
            maxs.append(max(nums[i:i+k]))
        return maxs
```
我这个好像慢一点。
另外可以试试题解里边的优化，python能跑到168ms左右

2019-12-14 03:43 UTC, YinDongFang commented on Week_01/G20190343020227/LeetCode_66_0227.py
> +        return [int(j) for j in str(int(''.join('%s' % i for i in digits))+1)]
👍

2019-12-15 03:35 UTC, xiaosimaqian commented on Week_01/G20190343020227/LeetCode_15_0227.py
> +        return res
学习了，有的操作符前后没有空格。

2019-12-15 04:23 UTC, momo5566 requested changes

2019-12-15 04:23 UTC, moi777 commented on Week_01/G20190343020227/LeetCode_189_0227.py
> +        nums[:] = nums[n-k:] + nums[:n-k]
厉害！写了那么多题！我的代码能力其实挺弱的，如果没有题目、解题思路、注释我看不懂……

2019-12-15 12:46 UTC, congve1 commented on Week_01/G20190343020227/LeetCode_239_0227.py
> +        for i in range(0,length):
0没有啥必要写

2019-12-15 12:48 UTC, congve1 commented on Week_01/G20190343020227/LeetCode_26_0227.py
> +        if len(nums)==0: return 0
我一般习惯写 if not nums: return 0. 感觉更简洁一些

2019-12-17 12:03 UTC, merged